# ============================================================
# Setup Secrets trong AWS Secrets Manager
# ============================================================
# Script nay tao/gia han cac secrets can thiet cho ECS tasks.
# Can chay SAU KHI terraform apply (vi secret ARNs duoc tao boi module secrets).
# ============================================================

param(
    [string]$Region = "ap-southeast-1",
    [string]$WandbApiKey = "",
    [string]$DatabaseUrl = "",
    [string]$MetricsToken = "",
    [string]$PrometheusToken = ""
)

$ErrorActionPreference = "Stop"

# ----- Auto-generate tokens neu khong truyen vao -----
function New-RandomToken {
    param([int]$Length = 32)
    $bytes = New-Object byte[] $Length
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return [Convert]::ToBase64String($bytes).Substring(0, $Length)
}

Write-Host "[1/4] Tu sinh cac token neu can..." -ForegroundColor Cyan
if ([string]::IsNullOrEmpty($MetricsToken)) {
    $MetricsToken = New-RandomToken -Length 40
    Write-Host "  Generated METRICS_TOKEN: $($MetricsToken.Substring(0,8))..." -ForegroundColor Yellow
}
if ([string]::IsNullOrEmpty($PrometheusToken)) {
    $PrometheusToken = New-RandomToken -Length 40
    Write-Host "  Generated PROMETHEUS_PUSH_TOKEN: $($PrometheusToken.Substring(0,8))..." -ForegroundColor Yellow
}

# ----- Lay secret ARNs tu terraform output -----
Write-Host "[2/4] Lay secret ARNs tu Terraform..." -ForegroundColor Cyan
Set-Location $PSScriptRoot\..\envs\prod

$outputs = terraform output -json 2>&1 | ConvertFrom-Json
if ($LASTEXITCODE -ne 0) {
    Write-Host "  FAIL: Chay terraform apply truoc" -ForegroundColor Red
    exit 1
}

$secretArns = $outputs.secret_arns.value
Write-Host "  Found $($secretArns.PSObject.Properties.Count) secret ARNs" -ForegroundColor Green

# ----- Upsert secrets -----
function Set-AwsSecret {
    param([string]$Arn, [string]$Value, [string]$Name)
    if ([string]::IsNullOrEmpty($Value)) {
        Write-Host "  SKIP $Name (empty value)" -ForegroundColor Yellow
        return
    }
    Write-Host "  Setting $Name..." -ForegroundColor Cyan
    $secretBytes = [System.Text.Encoding]::UTF8.GetBytes($Value)
    $tmpFile = New-TemporaryFile
    try {
        [System.IO.File]::WriteAllBytes($tmpFile.FullName, $secretBytes)
        aws secretsmanager put-secret-value `
            --secret-id $Arn `
            --secret-string file://$($tmpFile.FullName) `
            --region $Region | Out-Null
    } finally {
        Remove-Item $tmpFile.FullName -Force -ErrorAction SilentlyContinue
    }
    if ($LASTEXITCODE -eq 0) {
        Write-Host "    OK" -ForegroundColor Green
    } else {
        Write-Host "    FAIL" -ForegroundColor Red
    }
}

Write-Host "[3/4] Cap nhat secret values..." -ForegroundColor Cyan
Set-AwsSecret -Arn $secretArns.wandb_api_key         -Value $WandbApiKey         -Name "WANDB_API_KEY"
Set-AwsSecret -Arn $secretArns.database_url          -Value $DatabaseUrl          -Name "DATABASE_URL"
Set-AwsSecret -Arn $secretArns.metrics_token         -Value $MetricsToken         -Name "METRICS_TOKEN"
Set-AwsSecret -Arn $secretArns.prometheus_push_token -Value $PrometheusToken     -Name "PROMETHEUS_PUSH_TOKEN"

# ----- Save tokens to file (developer convenience) -----
Write-Host "[4/4] Luu tokens de tham khao local..." -ForegroundColor Cyan
$tokensFile = "$PSScriptRoot\..\..\secrets-local.env"
@"
# Generated by setup-secrets.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# LUY Y: File nay KHONG commit len git. Da add vao .gitignore.
METRICS_TOKEN=$MetricsToken
PROMETHEUS_PUSH_TOKEN=$PrometheusToken
# WANDB_API_KEY=<dien vao neu co>
# DATABASE_URL=<dien vao neu co>
"@ | Set-Content -Path $tokensFile -Encoding UTF8

Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "Secrets setup HOAN TAT!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "Tokens saved to: $tokensFile" -ForegroundColor Cyan
Write-Host ""
Write-Host "QUAN TRONG:" -ForegroundColor Yellow
Write-Host "  - File secrets-local.env KHONG duoc commit" -ForegroundColor Yellow
Write-Host "  - Neu cap nhat token moi, restart ECS service de pick up:" -ForegroundColor White
Write-Host "    aws ecs update-service --cluster cooksmart-prod --service cooksmart-prod-yolo-svc --force-new-deployment --region $Region" -ForegroundColor White